import 'package:drift/drift.dart';
import 'package:firebase_auth/firebase_auth.dart' as fb;
import 'package:flutter/foundation.dart';
import 'package:google_sign_in/google_sign_in.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';
import 'package:uuid/uuid.dart';

import '../../core/constants/app_constants.dart';
import '../../core/utils/preferences_provider.dart';
import '../../data/database/app_database.dart';
import '../../data/datasources/local/database_helper.dart';

part 'auth_provider.g.dart';

class AuthState {
  const AuthState({
    this.userId,
    this.displayName,
    this.firebaseUid,
    this.preferredUnit = 'kg',
    this.isLoggedIn = false,
    this.isOfflineUser = false,
    this.error,
  });

  final String? userId;
  final String? displayName;
  final String? firebaseUid;
  final String preferredUnit;
  final bool isLoggedIn;
  final bool isOfflineUser;
  final String? error;

  static const unauthenticated = AuthState();

  AuthState copyWith({
    String? userId,
    String? displayName,
    String? firebaseUid,
    String? preferredUnit,
    bool? isLoggedIn,
    bool? isOfflineUser,
    String? error,
  }) =>
      AuthState(
        userId: userId ?? this.userId,
        displayName: displayName ?? this.displayName,
        firebaseUid: firebaseUid ?? this.firebaseUid,
        preferredUnit: preferredUnit ?? this.preferredUnit,
        isLoggedIn: isLoggedIn ?? this.isLoggedIn,
        isOfflineUser: isOfflineUser ?? this.isOfflineUser,
        error: error,
      );
}

@Riverpod(keepAlive: true)
class AuthNotifier extends _$AuthNotifier {
  static const _uuid = Uuid();

  @override
  AuthState build() {
    final prefs = ref.read(sharedPreferencesProvider);
    final userId = prefs.getString('user_id');
    if (userId == null) return AuthState.unauthenticated;
    return AuthState(
      userId: userId,
      displayName: prefs.getString('user_name'),
      firebaseUid: prefs.getString('firebase_uid'),
      preferredUnit: prefs.getString('preferred_unit') ?? 'kg',
      isLoggedIn: true,
      isOfflineUser: prefs.getBool('is_offline_user') ?? false,
    );
  }

  /// Google Sign-In via Firebase.
  ///
  /// Uses google_sign_in 7.x API: GoogleSignIn.instance.initialize() reads the
  /// Web Client ID from the string resources generated by the google-services
  /// Gradle plugin (from google-services.json) — no hardcoded client ID needed.
  Future<void> signInWithGoogle() async {
    if (!kFirebaseAvailable) {
      state = state.copyWith(
          error: 'Google Sign-In requires internet — try "Continue without account".');
      return;
    }
    try {
      final gsi = GoogleSignIn.instance;
      await gsi.initialize(); // reads default_web_client_id from string resources
      final account = await gsi.authenticate();

      // In google_sign_in 7.x, authentication is a sync getter populated during authenticate()
      final idToken = account.authentication.idToken;
      final credential = fb.GoogleAuthProvider.credential(idToken: idToken);

      final result =
          await fb.FirebaseAuth.instance.signInWithCredential(credential);
      final fbUser = result.user;
      if (fbUser == null) return;

      final userId = await _upsertUserInDb(
        id: fbUser.uid,
        firebaseUid: fbUser.uid,
        name: fbUser.displayName ?? 'Athlete',
      );

      final prefs = ref.read(sharedPreferencesProvider);
      await prefs.setString('user_id', userId);
      await prefs.setString('user_name', fbUser.displayName ?? 'Athlete');
      await prefs.setString('firebase_uid', fbUser.uid);
      await prefs.setBool('is_offline_user', false);

      state = AuthState(
        userId: userId,
        displayName: fbUser.displayName,
        firebaseUid: fbUser.uid,
        isLoggedIn: true,
        isOfflineUser: false,
      );
    } on GoogleSignInException catch (e) {
      debugPrint('[IronLog] Google Sign-In: ${e.code} — ${e.description}');
      // Don't show error snackbar for user-initiated cancellation
      if (e.code != GoogleSignInExceptionCode.canceled) {
        state = state.copyWith(error: 'Sign-in failed: ${e.description ?? e.code.name}');
      }
    } catch (e) {
      debugPrint('[IronLog] Google Sign-In error: $e');
      state = state.copyWith(error: e.toString());
    }
  }

  /// Skips Firebase — creates a local UUID user for offline-only operation.
  Future<void> continueOffline() async {
    final id = _uuid.v4();
    final name = ref.read(sharedPreferencesProvider).getString('draft_name') ??
        'Athlete';

    await _upsertUserInDb(id: id, name: name);

    final prefs = ref.read(sharedPreferencesProvider);
    await prefs.setString('user_id', id);
    await prefs.setString('user_name', name);
    await prefs.setBool('is_offline_user', true);

    state = AuthState(
      userId: id,
      displayName: name,
      isLoggedIn: true,
      isOfflineUser: true,
    );
  }

  Future<void> signOut() async {
    if (kFirebaseAvailable) {
      try {
        await fb.FirebaseAuth.instance.signOut();
        await GoogleSignIn.instance.signOut();
      } catch (_) {}
    }

    final prefs = ref.read(sharedPreferencesProvider);
    await prefs.remove('user_id');
    await prefs.remove('user_name');
    await prefs.remove('firebase_uid');
    await prefs.remove('is_offline_user');

    state = AuthState.unauthenticated;
  }

  /// Updates the draft profile fields in SharedPreferences during onboarding.
  Future<void> saveDraftProfile({
    String? name,
    int? age,
    double? weightKg,
    double? heightCm,
    String? preferredUnit,
  }) async {
    final prefs = ref.read(sharedPreferencesProvider);
    if (name != null) await prefs.setString('draft_name', name);
    if (age != null) await prefs.setInt('draft_age', age);
    if (weightKg != null) await prefs.setDouble('draft_weight_kg', weightKg);
    if (heightCm != null) await prefs.setDouble('draft_height_cm', heightCm);
    if (preferredUnit != null) {
      await prefs.setString('preferred_unit', preferredUnit);
      state = state.copyWith(preferredUnit: preferredUnit);
    }
  }

  Future<void> saveGoal({String? description, double? targetWeightKg}) async {
    final prefs = ref.read(sharedPreferencesProvider);
    if (description != null) {
      await prefs.setString('draft_goal_desc', description);
    }
    if (targetWeightKg != null) {
      await prefs.setDouble('draft_goal_weight_kg', targetWeightKg);
    }
  }

  /// Upserts a user row from draft prefs after auth. Returns the userId.
  Future<String> _upsertUserInDb({
    required String id,
    String? firebaseUid,
    String? name,
  }) async {
    final prefs = ref.read(sharedPreferencesProvider);
    final db = ref.read(appDatabaseProvider);
    final now = DateTime.now().millisecondsSinceEpoch;

    await db.userDao.upsertUser(UsersCompanion.insert(
      id: id,
      name: name ??
          prefs.getString('draft_name') ??
          prefs.getString('user_name') ??
          'Athlete',
      createdAt: now,
      updatedAt: now,
      firebaseUid: Value(firebaseUid),
      age: Value(prefs.getInt('draft_age')),
      weightKg: Value(prefs.getDouble('draft_weight_kg')),
      heightCm: Value(prefs.getDouble('draft_height_cm')),
      goalDescription: Value(prefs.getString('draft_goal_desc')),
      goalWeightKg: Value(prefs.getDouble('draft_goal_weight_kg')),
      preferredUnit:
          Value(prefs.getString('preferred_unit') ?? 'kg'),
    ));
    return id;
  }
}
